TrajectoryPlannerROS:

  holonomic_robot: false

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.15
  min_vel_x: 0.15
  min_in_place_vel_theta: 0.3
  escape_vel: -0.25
  meter_scoring: true
  pdist_scale: 0.4
  
