map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

#transform_tolerance: 0.3  #specified in amcl launch

inflation_radius: 0.55

#robot_radius: 0.25 # for chuck robot
footprint: [[-0.25, -0.20], [-0.25, 0.20], [0.25, 0.20], [0.25, -0.20]]  # for udacity Robot

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
